django/conf/project_template/project_name/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', '{{ project_name }}.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
)

djangoappengine/conf/project_template/project_name/urls.py
from django.conf.urls import patterns, include, url

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', '{{ project_name }}.views.home', name='home'),
    # url(r'^{{ project_name }}/', include('{{ project_name }}.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    # url(r'^admin/', include(admin.site.urls)),
)

muse/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings

admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'muse.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
		url(r'^', include('music_stream.urls')),
		(r'^accounts/', include('registration.backends.simple.urls')),
)

if not settings.DEBUG:
        urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

#test

music_stream/urls.py
from django.conf.urls import patterns, url
from django.conf import settings
from django.contrib import admin
from music_stream import views
from django.conf.urls.static import static

admin.autodiscover()

urlpatterns = patterns('',
		url(r'^serve/(?P<pk>.+)$', views.serve, name='serve'),
		url(r'^blob/', views.blob , name='blob'),
        url(r'^$', views.index, name='index'),
        url(r'^search$', views.search, name='search'),
        url(r'^upload$', views.upload, name='upload'),
        url(r'^album/(?P<album_name_slug>[\w\-]+)/$', views.album, name='album'),
        url(r'^artist/(?P<artist_name_slug>[\w\-]+)/$', views.artist, name='artist'),
        url(r'^playlist/(?P<playlist_name_slug>[\w\-]+)/$', views.playlist, name='playlist'),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


#'/serve/([^/]+)?'

music_stream/models.py
from django.db import models
from django.db.models import Model
from django.template.defaultfilters import slugify
from djangotoolbox.fields import ListField
from os.path import splitext
from mutagen.mp3 import MP3
from mutagen.id3 import ID3, TIT2, TPE1, COMM, TALB
from django.core.files.storage import FileSystemStorage
from django.core.files.storage import default_storage as storage
from os.path import splitext
from mutagen.mp3 import MP3
from mutagen.id3 import ID3, TIT2, TPE1, COMM

from google.appengine.ext import blobstore
from google.appengine.api import images

import hashlib

# class CustomStorage(FileSystemStorage):
# 	def get_available_name(self, file_name):
# 		return file_name
		
# 	def _save(self, file_name, content):
# 		if self.exists(file_name):
# 			#if the file exists, do not save the new file
# 			return file_name
# 		#if the file does not exist, save the file
# 		return super(CustomStorage, self)._save(file_name, content)		

class Song(models.Model):
	owner = models.CharField(max_length=30,default=None)
	shared = ListField()
	file_name = models.CharField(max_length=128)
	songfile = models.FileField(upload_to='music/%Y/%m/%d')
	md5sum = models.CharField(max_length=36,default=None)
	title = models.CharField(max_length=128,default='untitled')
	artist = models.CharField(max_length=128,default='unknown')
	album = models.CharField(max_length=128,default='unknown')
	track_num = models.PositiveSmallIntegerField(default=1)
	length = models.PositiveSmallIntegerField(default=0)
	artist_slug = models.SlugField(max_length=128,default='unknown')
	album_slug = models.SlugField(max_length=128,default='unknown')
	title_slug = models.SlugField(max_length=128,default='unknown')


	def __unicode__(self):
		return self.file_name

	def save(self, *args, **kwargs):
		#self.file_name = splitext(self.file_name)[0]
		if not self.pk: #file is new
			md5 = hashlib.md5()
			for chunk in self.songfile.chunks():
					md5.update(chunk)
			self.md5sum = md5.hexdigest()
		super(Song,self).save(*args, **kwargs)
	def saveTags(self, *args, **kwargs):
		super(Song,self).save(*args, **kwargs)

	def update(self):
		#s= serve_file(self, self.songfile, save_as=True)
		#s= "/serve/"+ str(self.pk)
		s=self.songfile.file.blobstore_info
		self.shared = []
		# s= blobstore.BlobInfo.get(r)
		# s= self.songfile.file.blobstore_info
		# s = images.get_serving_url(r)
		audiofile = ID3(s)
		mp3file = MP3(s)
		if "TIT2" in audiofile:
			self.title = str(audiofile["TIT2"])
		else:
			self.title = self.file_name
		if "TPE1" in audiofile:
			self.artist = str(audiofile["TPE1"])
		else:
			self.artist = 'Unknown'
		if "TALB" in audiofile:
			self.album = str(audiofile["TALB"])
		else:
			self.album = 'Unknown'
		self.artist_slug = slugify(self.artist)
		self.album_slug = slugify(self.album)
		self.title_slug = slugify(self.title)
		if not self.artist_slug:
			self.artist_slug = 'Unreadable'
		if not self.album_slug:
			self.album_slug = 'Unreadable'
		if not self.title_slug:
			self.title_slug = 'Unreadable'
		tmp = mp3file.info.length
		tmp = str(tmp).split(".",1)
		self.length = tmp[0]
		if "TRCK" in audiofile:
			tmp = audiofile["TRCK"]
		else:
			tmp = 1
		tmp = str(tmp).split("/",1)
		self.track_num = tmp[0]
		
		super(Song,self).save()
	def share(self, user):
		self.shared.append(user)
		super(Song,self).save()
	def deshare(self, user):
		self.shared.remove(user)
		super(Song,self).save()

class Result(models.Model):
	item = models.CharField(max_length=128,default='unknown')
	item_slug= models.SlugField(max_length=128,default='unknown')

class Playlist(models.Model):
	owner = models.CharField(max_length=30,default=None)
	name = models.CharField(max_length=30,default=None)
	name_slug = models.SlugField(max_length=128,default='unknown')
	songs = ListField()


	def __unicode__(self):
		return self.name


	def save(self, *args, **kwargs):
		self.name_slug = slugify(self.name)
		super(Playlist,self).save(*args, **kwargs)

	def add(self, song):

		self.songs.append(song)
		set(self.songs)
		super(Playlist, self).save()

	def remove(self, song):

		self.songs.remove(song)
		set(self.songs)
		super(Playlist, self).save()

music_stream/forms.py
# -*- coding: utf-8 -*-
from django import forms 
from music_stream.models import Song

class SongForm(forms.ModelForm):
	songfile = forms.FileField(
		label = 'Select a file'	
	)

	class Meta:
		model = Song
		fields=('songfile',)
		exclude=('file_name','title','artist','track_num')

music_stream/views.py
from django.shortcuts import render_to_response, render, redirect, get_object_or_404
from django.template import RequestContext
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from django.template.defaultfilters import slugify
from django.core.urlresolvers import reverse
from django.db.models import Q

from music_stream.models import  Song
from music_stream.models import Result
from music_stream.models import Playlist
from music_stream.forms import SongForm

import os
import urllib

from google.appengine.ext import blobstore
from google.appengine.ext import webapp
from google.appengine.ext.webapp import blobstore_handlers
from google.appengine.ext.webapp import template
from google.appengine.ext.webapp.util import run_wsgi_app

from filetransfers.api import prepare_upload
from filetransfers.api import serve_file


def index(request):
	upload_url = blobstore.create_upload_url('/')
	view_url = reverse('music_stream.views.index')
	if request.user.is_authenticated():
		error = ""
		songList = Song.objects.filter(owner=request.user.username)

		artists = set([s.artist for s in Song.objects.filter(owner=request.user.username)])
		artists = sorted(artists)
		artist_slugs = set([s.artist_slug for s in Song.objects.filter(owner=request.user.username)])
		artist_slugs = sorted(artist_slugs)
		albums = set([s.album for s in Song.objects.filter(owner=request.user.username)])
		albums = sorted(albums)
		album_slugs = set([s.album_slug for s in Song.objects.filter(owner=request.user.username)])
		album_slugs = sorted(album_slugs)
		zArtists = zip(artists,artist_slugs)
		zAlbums = zip(albums,album_slugs)
		playlists = set([p for p in Playlist.objects.filter(owner= request.user.username)])

		preShare = set([s for s in Song.objects.all()])
		sharedList = []
		for s in preShare:
			for t in s.shared:
				if str(request.user.username) == t:
					sharedList.append(s)
		if request.method == 'POST':
			if 'upload_submit' in request.POST:
				form = SongForm(request.POST, request.FILES)
				if form.is_valid():
					newsong = Song(owner=request.user.username, file_name=request.FILES['songfile'].name, songfile=request.FILES['songfile'])
					newsong.save()
					newsong.update()
				# Redirect to the document list after POST
					#return HttpResponse("SUCCESS")
					return HttpResponseRedirect(view_url)
			if 'purge_all' in request.POST:
				for s in songList:
					blobstore.delete(s.songfile.file.blobstore_info.key())
				songList.delete()
			if 'purge_selection' in request.POST:
				for s in songList:
					if str(s.id) in request.POST:
						blobstore.delete(s.songfile.file.blobstore_info.key())
						s.delete()
			if 'share' in request.POST:
				shar = request.POST['sharewith'].strip()
				if shar:
					for s in songList:
						if str(s.id) in request.POST:
							s.share(str(shar))
							#sharedList.append(s)
							# raise Exception("share")
			if 'deshar' in request.POST:
					for s in sharedList:
						if str(s.id) in request.POST:
							if s.owner == request.user.username:
								s.shared = []
								s.saveTags()
							else:
								s.deshare(str(request.user.username))
			if 'create' in request.POST:
				shar = request.POST['sharewith'].strip()
				if shar:
					checklists = set([p for p in Playlist.objects.filter(owner = request.user.username)])
					for c in checklists:
						if slugify(c.name) == slugify(str(shar)):
							error = "Name Used."
							break
							# raise Exception("FFS")
					else:
						newlist = Playlist(owner = request.user.username, name = str(shar))
						newlist.save()
						for s in songList:
							if str(s.id) in request.POST:
								newlist.add(s.id)
						for s in sharedList:
							if str(s.id) in request.POST:
								newlist.add(s.id)
			if 'delete' in request.POST:
				for p in set([p for p in Playlist.objects.filter(owner=request.user.username)]):
					if str(p.id) in request.POST:
						p.delete()


		
		for p in playlists:
			for s in p.songs:
				try:
					Song.objects.get(id=s)
				except:
					p.remove(s)
			q = p.songs[:]
			p.songs = []
			for s in q:
				p.songs.append(Song.objects.get(id=s))
		form = SongForm() # A empty, unbound forms

			# Load documents for the list page
		upload_url, upload_data = prepare_upload(request, view_url)
			# Render list page with the documents and the form
		# return render(request,'music_stream/index.html',context_dict)

		return render_to_response(
							'music_stream/index.html',
							{'error': error, 'songList': songList, 'form': form, 'upload_url': upload_url, 'upload_data': upload_data, 'sharedList': sharedList, 'playlists': playlists, 'zArtists':zArtists, 'zAlbums':zAlbums},
							context_instance=RequestContext(request)
							)
	else:
		return redirect('accounts/login', request)

def search(request):
	

	if request.user.is_authenticated():

		if request.method == 'POST':
			if 'query' in request.POST:
				context_dict = {}
				artists = set([s.artist for s in Song.objects.filter(owner=request.user.username)])
				artists = sorted(artists)
				artist_slugs = set([s.artist_slug for s in Song.objects.filter(owner=request.user.username)])
				artist_slugs = sorted(artist_slugs)
				albums = set([s.album for s in Song.objects.filter(owner=request.user.username)])
				albums = sorted(albums)
				album_slugs = set([s.album_slug for s in Song.objects.filter(owner=request.user.username)])
				album_slugs = sorted(album_slugs)
				zArtists = zip(artists,artist_slugs)
				zAlbums = zip(albums,album_slugs)
				playlists = set([p for p in Playlist.objects.filter(owner= request.user.username)])
				context_dict['zArtists'] = zArtists
				context_dict['zAlbums'] = zAlbums
				context_dict['playlists'] = playlists
				context_dict['artists'] = None
				context_dict['songs'] = None
				context_dict['albums'] = None
				context_dict['query'] = None
				query = request.POST['query'].strip()
				if query:
					query2 = str(slugify(query))
					artistz = set([s.artist for s in Song.objects.filter(owner=request.user.username)])
					for a in artistz.copy():
						if not(query in a) and not(query2 in str(slugify(a))):
							artistz.remove(a)
					albumz = set([s.album for s in Song.objects.filter(owner=request.user.username)])
					for a in albumz.copy():
						if not(query in a) and not(query2 in str(slugify(a))):
							albumz.remove(a)
					songs = set([s for s in Song.objects.filter(owner=request.user.username)])
					for a in songs.copy():
						if not(query in a.title) and not(query2 in str(slugify(a.title))):
							songs.remove(a)
					albums = []
					artists = []
					for a in albumz:
						b= Result(item=a, item_slug=slugify(a))
						albums.append(b)
					for a in artistz:
						b= Result(item=a, item_slug=slugify(a))
						artists.append(b)

					context_dict['query'] = query
					context_dict['artists'] = artists
					context_dict['songs'] = songs
					context_dict['albums'] = albums
					return render(request,'music_stream/search.html',context_dict)

				else:
					return HttpResponseRedirect(reverse('music_stream.views.index'))
			else:
				return HttpResponseRedirect(reverse('music_stream.views.index'))
		else:
			return HttpResponseRedirect(reverse('music_stream.views.index'))

	else:
		return redirect('accounts/login', request)


def album(request,album_name_slug):
	context_dict = {}
	artists = set([s.artist for s in Song.objects.filter(owner=request.user.username)])
	artists = sorted(artists)
	artist_slugs = set([s.artist_slug for s in Song.objects.filter(owner=request.user.username)])
	artist_slugs = sorted(artist_slugs)
	albums = set([s.album for s in Song.objects.filter(owner=request.user.username)])
	albums = sorted(albums)
	album_slugs = set([s.album_slug for s in Song.objects.filter(owner=request.user.username)])
	album_slugs = sorted(album_slugs)
	zArtists = zip(artists,artist_slugs)
	zAlbums = zip(albums,album_slugs)
	playlists = set([p for p in Playlist.objects.filter(owner= request.user.username)])
	context_dict['zArtists'] = zArtists
	context_dict['zAlbums'] = zAlbums
	context_dict['playlists'] = playlists
	songs = Song.objects.filter(owner=request.user.username).filter(album_slug=album_name_slug)
	if songs:
		context_dict['songs'] = songs
		context_dict['self'] = album_name_slug
		context_dict['album'] = songs[0].album

		if request.method == 'POST':
			if 'purge_all' in request.POST:
				for s in songs:
					blobstore.delete(s.songfile.file.blobstore_info.key())
				songs.delete()
			if 'purge_selection' in request.POST:
				for s in songs:
					if str(s.id) in request.POST:
						blobstore.delete(s.songfile.file.blobstore_info.key())
						s.delete()


		return render(request, 'music_stream/album.html',context_dict)
	else:
		return HttpResponseRedirect(reverse('music_stream.views.index'))

def playlist(request, playlist_name_slug):
	context_dict = {}
	artists = set([s.artist for s in Song.objects.filter(owner=request.user.username)])
	artists = sorted(artists)
	artist_slugs = set([s.artist_slug for s in Song.objects.filter(owner=request.user.username)])
	artist_slugs = sorted(artist_slugs)
	albums = set([s.album for s in Song.objects.filter(owner=request.user.username)])
	albums = sorted(albums)
	album_slugs = set([s.album_slug for s in Song.objects.filter(owner=request.user.username)])
	album_slugs = sorted(album_slugs)
	zArtists = zip(artists,artist_slugs)
	zAlbums = zip(albums,album_slugs)
	playlists = set([p for p in Playlist.objects.filter(owner= request.user.username)])
	context_dict['zArtists'] = zArtists
	context_dict['zAlbums'] = zAlbums
	context_dict['playlists'] = playlists
	playlist = Playlist.objects.filter(owner=request.user.username).get(name_slug = playlist_name_slug)
	if playlist:
		
		if request.method == 'POST':
			if 'remove' in request.POST:
				for s in playlist.songs:
					if str(s) in request.POST:
						playlist.remove(s);
			if 'delete' in request.POST:
				playlist.delete()
				return HttpResponseRedirect(reverse('music_stream.views.index'))

templates/music_stream/album.html
{% extends "base.html" %}

{% block body_block %}
	
	

    {% if songs %}
    <h4>{{ album }}</h4>
    <!-- <audio preload></audio> -->
        <form action="{% url 'album' album_name_slug=self %}" method = "post" enctype = "multipart/form-data">
            {% csrf_token %}
			<div class="table-responsive">
				<table id="myTable" class="sortable-theme-bootstrap table-hover" data-sortable >
					<thead>
					
								<th data-sorted="false" data-sorted-direction="descending" class="col-md-4" style="font-weight:bold;"> TITLE </th>
								<th data-sorted="false" class="col-xs-1 col-md-1 glyphicon glyphicon-time" style="font-weight:bold;"> </th>
  							<th data-sorted="false" class="col-md-3" style="font-weight:bold;"> ALBUM </th>
								<th data-sorted="false" class="col-md-3" style="font-weight:bold;"> ARTIST </th>
								<th data-sorted="false" class="col-md-5" style="font-weight:bold;"> DOWNLOAD </th>
						
					</thead>
					{% load filetransfers %}
					{% for song in songs %}
					{% url "music_stream.views.serve" pk=song.pk as fallback_url %}	
					<tr>
								<td id = "table-value" class = "song" data-value="{{song.title}}"> <a href="#" data-src="{% firstof upload.file|public_download_url fallback_url %}" class="song-name">{{ song.title}}</a></td>
								<td id="table-duration{{forloop.counter}}" > 
									<script type="text/javascript"> 
									 var a = "{{song.length}}";
									 var display = document.getElementById("table-duration" + {{forloop.counter}});
									 var duration = Math.floor(a / 60) + ":";
									 if(a % 60 < 10) {
										var sec = "0" + (a % 60);
										duration += sec;
									 }
									 else {
										var sec = a % 60;
										duration += sec;
									 }										 										
									 display.innerHTML = duration;																		
									</script>
								</td>
								<td> <a href="{% url 'album' album_name_slug=song.album_slug %}">{{song.album}}</a></td>
								<td> <a href="{% url 'artist' artist_name_slug=song.artist_slug %}">{{song.artist}}</a></td>
								<td><a href="{% firstof upload.file|public_download_url fallback_url %}">DL</a>&nbsp;&nbsp;&nbsp;<input type="checkbox" name ="{{ song.id }}" value = "{{ song.title }}"></td>
					</tr>
					{% endfor %}
				</table>    
			</div>


		</div><br>
		<input id="dsel" class="btn btn-primary" type="submit" name="purge_selection" value="Delete Selection" />
		<!-- <input class="btn btn-primary" type="submit" name="purge_all" value="DELETE ALL" /> -->
	</form>
	{% else %}
		<p> Requested Album is Empty </p>
    {% endif %}

    <table id="Table2"></table>

{% endblock %}

templates/music_stream/artist.html
{% extends "base.html" %}

{% block body_block %}


    <h3>{{ artist }}</h3>
        {% if albums %}
            <h4>Albums</h4>
                {% for album in albums %}
                    <p><a href="/album/{{ album.item_slug }}">{{ album.item }}</a></p>
                {% endfor %}
        {% endif %}

        

        {% if songs %}
            <h4>All Songs</h4>
            <!-- <audio preload></audio> -->
            <form action="{% url 'artist' artist_name_slug=self %}" method = "post" enctype = "multipart/form-data">
            {% csrf_token %}
            <div class="table-responsive">
                <table id="myTable" class="sortable-theme-bootstrap table-hover" data-sortable >
                    <thead>
                    
                                <th data-sorted="false" data-sorted-direction="descending" class="col-md-4" style="font-weight:bold;"> TITLE </th>
																<th data-sorted="false" class="col-xs-1 col-md-1 glyphicon glyphicon-time" style="font-weight:bold;"> </th>
   <th data-sorted="false" class="col-md-3" style="font-weight:bold;"> ALBUM </th>
                                <th data-sorted="false" class="col-md-3" style="font-weight:bold;"> ARTIST </th>
                                <th data-sorted="false" class="col-md-5" style="font-weight:bold;"> DOWNLOAD </th>
                        
                    </thead>
                    {% load filetransfers %}
                    {% for song in songs %}
                    {% url "music_stream.views.serve" pk=song.pk as fallback_url %} 
                    <tr>
												<td class = "song" data-value="{{song.title}}"> <a href="#" data-src="{% firstof upload.file|public_download_url fallback_url %}" class="song-name">{{ song.title}}</a></td>
												<td id="table-duration{{forloop.counter}}" > 
													<script type="text/javascript"> 
													 var a = "{{song.length}}";
													 var display = document.getElementById("table-duration" + {{forloop.counter}});
													 var duration = Math.floor(a / 60) + ":";
													 if(a % 60 < 10) {
														var sec = "0" + (a % 60);
														duration += sec;
													 }
													 else {
														var sec = a % 60;
														duration += sec;
													 }										 										
													 display.innerHTML = duration;																		
													</script>
												 </td>
	 <td> <a href="{% url 'album' album_name_slug=song.album_slug %}">{{song.album}}</a></td>
                                <td> <a href="{% url 'artist' artist_name_slug=song.artist_slug %}">{{song.artist}}</a></td>
                                <td><a href="{% firstof upload.file|public_download_url fallback_url %}">DL</a>&nbsp;&nbsp;&nbsp;<input type="checkbox" name ="{{ song.id }}" value = "{{ song.title }}"></td>
                    </tr>
                    {% endfor %}
                </table>    
            </div>


        </div><br>
        <input id="dsel" class="btn btn-primary" type="submit" name="purge_selection" value="Delete Selection" />
        <!-- <input class="btn btn-primary" type="submit" name="purge_all" value="DELETE ALL" /> -->
    </form>
        {% else %}
        <p> Requested Artist has no Songs </p>
        {% endif %}
<table id="Table2"></table>
{% endblock %}

templates/music_stream/list.html
<!DOCTYPE html>
{% extends "base.html" %}
<html>
    <head>
        <meta charset="utf-8">
        <title>Blobstore Total Access</title>  


      
    </head>
    <body>
        {% block body_block %}
    <!-- List of uploaded documents -->
    <!-- <audio preload></audio> -->
    {% if songList %}

        <form action="{% url 'blob' %}" method = "post" enctype = "multipart/form-data">
            {% csrf_token %}
        <div class="table-responsive">
                <table id="myTable" class="sortable-theme-bootstrap table-hover" data-sortable >
                    <thead>
                    
                                <th data-sorted="false" data-sorted-direction="descending" class="col-md-4" style="font-weight:bold;"> TITLE </th>
                                <th data-sorted="false" class="col-xs-1 col-md-1 glyphicon glyphicon-time" style="font-weight:bold;"> </th>
                                <th data-sorted="false" class="col-md-3" style="font-weight:bold;"> ALBUM </th>
                                <th data-sorted="false" class="col-md-3" style="font-weight:bold;"> ARTIST </th>
                                <th data-sorted="false" class = "col-md-5" style="font-weight:bold;"> SELECT </th>
                        
                    </thead>
                    {% load filetransfers %}
                    {% for song in songList %}
                    {% url "music_stream.views.serve" pk=song.pk as fallback_url %} 
                    <tr>
                                <td class = "song" data-value="{{song.title}}"> <a href="#" data-src="{% firstof upload.file|public_download_url fallback_url %}" class="song-name">{{ song.title}}</a></td>
                                <td id="table-duration{{forloop.counter}}" > 
                                    <script type="text/javascript"> 
                                     var a = "{{song.length}}";
                                     var display = document.getElementById("table-duration" + {{forloop.counter}});
                                     var duration = Math.floor(a / 60) + ":";
                                     if(a % 60 < 10) {
                                        var sec = "0" + (a % 60);
                                        duration += sec;
                                     }
                                     else {
                                        var sec = a % 60;
                                        duration += sec;
                                     }                                                                              
                                     display.innerHTML = duration;                                                                      
                                    </script>
                                </td>
                                <td> {{song.album}}</td>
                                <td> {{song.artist}}</td>
                                <td><a href="{% firstof upload.file|public_download_url fallback_url %}">DL</a>&nbsp;&nbsp;&nbsp;<input type="checkbox" name ="{{ song.id }}" value = "{{ song.title }}"></td>
                    </tr>
                    {% endfor %}
                </table>    
            </div>
            <input style="width:30%;" class="btn btn-default btn-md" type="submit" name="purge_selection" value="Purge Selected" />
            <input style="width:30%;" class="btn btn-default btn-md" type="submit" name="purge_all" value="PURGE ALL" />
        </form>
        {{error}}
    {% else %}
        <p>No documents.</p>
    {% endif %}
    <table id="Table2"></table>
{% endblock %}
{% block title_block %}Blobstore Total Access{% endblock %}
{% block noside %}{% endblock %}
    
    </body>
</html> 

templates/music_stream/upload.html
{% extends "base.html" %}

{% block body_block %}


    <h3 style="color:black;font-size:16px;">Add Songs</h3>
        <!-- Upload form. Note enctype attribute! -->
        {% load filetransfers %}
        <form action="{{ upload_url }}" method="post" enctype="multipart/form-data">

            {% csrf_token %}
            {% render_upload_data upload_data %}
            <table>{{ form }}</table>
           <!-- <input style="width:30%;margin-bottom:20px;"  id="id_songfile" name="songfile" type="file" /> -->
           <input style="width:30%;" class="btn btn-default btn-md" type="submit" name="upload_submit" value="Upload" />
        </form>

{% endblock %}